# docker compose file to build all components of the albumartdb service

version: '3.1'

services:

  mongo:
    image: mongo
    container_name: ${MONGO_CONTAINER_NAME}
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}

  mongo-express:
    image: mongo-express
    container_name: mongo-express-container
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}

  backend:
    image: albumartdb/backend:latest
    container_name: backend-container
    restart: always
    stdin_open: true # docker run -i
    tty: true        # docker run -t

  frontend:
    image: albumartdb/frontend:latest
    container_name: frontend-container
    restart: always
    ports:
      - 3000:3000
    stdin_open: true # docker run -i
    tty: true        # docker run -t
